package template_rec;

import java.time.format.DateTimeFormatter

import com.ftn.sbnz.model.models.Recommendation;
import java.time.format.DateTimeFormatter;

rule "Visualize Recommendation"
when
    $r: Recommendation()
then
    String optimalTimeStr = ($r.getRecommendedPublishTime() != null) ?
                            $r.getRecommendedPublishTime().format(DateTimeFormatter.ofPattern("EEEE HH:mm")) : "N/A";

    System.out.println(
        "--- TEMPLATE RULE: VISUALIZE --- \n" +
        "Displaying post " + $r.getPostId() + " for user " + $r.getUserId() + "\n" +
        "  | Priority: " + String.format("%.2f", $r.getPriorityScore()) + "\n" +
        "  | Predicted Engagement: " + String.format("%.3f", $r.getPredictedEngagement()) + "\n" +
        "  | Optimal time: " + optimalTimeStr + "\n" +
        "  | Reasoning: " + $r.getReasoning() + "\n"
    );
end

rule "Personalize By Interest"
when
    $r: Recommendation( category != null )
then
    System.out.println(
        "--- TEMPLATE RULE: PERSONALIZE --- \n" +
        "Personalized recommendation for user " + $r.getUserId() +
        " generated for interest category: " + $r.getCategory() + ".\n"
    );
end